# Generated by Django 5.0.2 on 2024-02-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_student_course_id_course_enrolment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_classes',
            name='class_number',
            field=models.IntegerField(),
        ),
    ]
