# Generated by Django 5.0.2 on 2024-02-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_classes_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended_date',
            field=models.DateField(),
        ),
    ]
