# Generated by Django 5.0 on 2024-02-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_attendance_attended_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_enrolment',
            options={'verbose_name': 'Student Course Enrolment'},
        ),
        migrations.AlterUniqueTogether(
            name='course_enrolment',
            unique_together={('course_id', 'student_id')},
        ),
    ]
