# Generated by Django 5.0 on 2024-02-15 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_enrolment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Student Enrolment Course'},
        ),
        migrations.AlterModelOptions(
            name='course_classes',
            options={'verbose_name': 'Course Lecture Classes'},
        ),
        migrations.AlterModelOptions(
            name='course_enrolment',
            options={'verbose_name': 'Student Enrolment Course'},
        ),
        migrations.AlterUniqueTogether(
            name='course_enrolment',
            unique_together=set(),
        ),
    ]
