# Generated by Django 5.0 on 2024-02-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Student Course Wise Attendance'},
        ),
    ]
